In [1]:
import numpy as np
print("numpy loaded successfully")

numpy loaded successfully


In [2]:
np.array(1)
print(type(np.array(1)))

<class 'numpy.ndarray'>


In [3]:
arr = np.array(([1, 2, 3, 4, 5],[6, 7, 8, 9, 10]))
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [4]:
print(len(arr))  # python function Output: 10 )

2


In [5]:
# attribute 
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 5)
2
10
int64


In [6]:
# methods 
print(np.arange(0,10))  # start,  stop, step

[0 1 2 3 4 5 6 7 8 9]


In [7]:
np.random.rand(3,4)

array([[0.6006169 , 0.62576604, 0.40618471, 0.51485942],
       [0.73294576, 0.84861327, 0.88863514, 0.97547136],
       [0.99210689, 0.89798548, 0.65035674, 0.34379238]])

In [8]:
np.random.randint(0,10,10)   # start, stop, size

array([8, 8, 5, 7, 9, 4, 4, 1, 1, 1], dtype=int32)

In [9]:
# zeros 
np.zeros((2,4,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# min, max, argmax, argmin
print(arr)
arr.ravel
arr.flatten

#min(arr)  # py func
np.min(arr)   # np method max

#index finding
np.argmax(arr)  # argmax

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


np.int64(9)

In [12]:
#mean std 
print(arr)
arr+arr

list1=[1,2,3,4,5]
list1+list1    #concat

arr.mean()
arr.std()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


np.float64(2.8722813232690143)